### ISSUE TITLE
Cannot access Sequence methods

### ISSUE THREAD

**Issue by dridk** [BIG-Tools/BigBrowser#54] opened 2016-03-13 23:25 UTC
I excepted to have methods avaible from this way: 

```
    Sequence seq("ACGT");
    qDebug()<<seq.reverseComplement();
```

Not working actually

**Comment by natir** [comment] 2016-03-14 07:03
Yes it's impossible by design. Sequence is just a typedef because we can't inherite to Qt and STL container, and write a wrapper is long and create bug task. 

But this run : 

``` c++
big::core::Sequence seq("ACGT");
qDebug()<<big::core::sequence::reverseComplement(seq);
```

**Comment by natir** [comment] 2016-03-14 21:23
I can close this issue @dridk ?

**Comment by dridk** [comment] 2016-03-14 21:29
Yes.  But i will create a new one for seq->name() et seq->setName ("chr4")

**Closed as completed** 2016-03-15 15:34 UTC
Labels: Dev Task, core
